backend:
  name: github
  repo: ptrbrynt/ptrbrynt.com
  branch: main
  base_url: https://ptrbrynt.com
  auth_endpoint: /api/auth

media_folder: "images"
public_folder: "public"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
